#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
'''
    Title: BC extraction
    Date last modified: 2020/09/16
    Python Version: 3.6.2
'''
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

include:
    '/DATA/usr/m.trauernicht/projects/prime_TF_reporters/data/gcf7866/raw-data-analysis/config.py'

# Rules -----------------------------------------------------------------------

rule all:
    input:
        expand('../results/{ecn}_barcode_counts.tsv', ecn = ECN)


# Extract barcodes from cDNA/pDNA SE fastq files
rule extract_barcodes_from_fq:
    input:
        fq = ECN_DIR + S1
    output:
        tsv = '../results/{ecn}_barcodes.tsv'
    log:
        'logs/{ecn}_extract_barcodes_from_fq.log'
    conda:
        '/DATA/usr/m.trauernicht/projects/prime_TF_reporters/data/gcf7866/raw-data-analysis/environment.yaml'
    script:
        '/DATA/usr/m.trauernicht/projects/prime_TF_reporters/data/gcf7866/raw-data-analysis/mt20220524_bc-counts.py'

# Cluster cDNA/pDNA barcodes with Starcode

rule cluster_ecn_barcodes:
    input:
        starcode_in = '../results/{ecn}_barcodes.tsv'
    output:
        ofn = '../results/{ecn}_barcode_counts.tsv',
    log:
        'logs/{ecn}_cluster_ecn_barcodes.log'
    conda:
        '/DATA/usr/m.trauernicht/projects/prime_TF_reporters/data/gcf7866/raw-data-analysis/environment.yaml'
    threads: 50
    shell:
        'starcode --threads {threads} --print-clusters -i {input.starcode_in} --dist 1 | \
        sort -k1,1 > {output.ofn}'
